title: Islam Mesabah
logo: /assets/img/mypic.jpg
email: islam.r.mesabah@gmail.com
description: "[ Research Assistant | Computer Science master's student ] at DFKI and TU Kaiserslautern"
favicon: true
color-scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - icon: <i class="fa-brands fa-researchgate"></i>
    link: https://www.researchgate.net/profile/Islam-Mesabah
  - icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/islammesabah
  - icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/islammesabah/
  - icon: <i class="fa-brands fa-twitter"></i>
    link: https://twitter.com/islam_mesabah
  - icon: <i class="fa-brands fa-youtube"></i>
    link: https://www.youtube.com/@islammesabah
    

navigation:
  - name: Home
    link: ./index.html
    sublist:
      - name: Experience
        link: ./index.html#experience
      - name: Education
        link: ./index.html#education
      - name: Awards
        link: ./index.html#awards
      - name: Puplication
        link: ./index.html#puplication
      - name: Volunteer
        link: ./index.html#volunteer
  - name: Projects
    link: ./projects
