title: Islam Mesabah
logo: /assets/img/mypic.jpg
email: islam.r.mesabah@gmail.com
description: Islam Mesabah is a research assistant in the Machine Learning Group at TU Kaiserslautern led by Prof. Dr. Marius Kloft and Jun.-Prof. Dr. Sophie Fellenz. He is studying Master's in Computer Science at TU Kaiserslautern. He finished his Bachelor’s degree In Computer science and engineering from The German university in Cairo(GUC), Egypt. He has also worked in the GUC as a teaching assistant after graduating.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vaibhavvikas
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas

navigation:
  - name: Readme
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
