title: Islam Mesabah
logo: /assets/img/mypic.jpg
email: islam.r.mesabah@gmail.com
description: Research Assistant, Computer Science master's student at TU Kaiserslautern
favicon: true
color-scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/islammesabah
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/islamkaloop

navigation:
  - name: Home
    link: ./index.html
    sublist:
      - name: Experience
        link: ./index.html#Experience
      - name: Education
        link: ./index.html#Education
      - name: Awards
        link: ./index.html#Awards
      - name: Puplication
        link: ./index.html#Puplication
      - name: Projects
        link: ./index.html#Projects
      - name: Volunteer
        link: ./index.html#Volunteer
      - name: Statistics
        link: ./index.html#Statistics
  
